config/routes.rb
Rails.application.routes.draw do

  root 'rides#index'
  get 'statistics/index'

  resources :rides

end

app/models/corporation.rb
# Corporation model - taxi corporation names
class Corporation < ActiveRecord::Base
  scope :active, -> { where(status: true) }

  has_many :rides

  validates :name, presence: true
  validates :name, uniqueness: { case_sensitive: false }
  validates :name, length: { maximum: 256 }
end

app/models/ride.rb
# Ride model - list of rides
class Ride < ActiveRecord::Base
  include Geo

  default_scope { order(date: :asc) }
  scope :by_user_with_corporations, -> (user) { includes(:corporation).where(user: user) }
  scope :by_user, -> (user) { where(user: user) }
  scope :current_week, -> { where('date >= :date', date: Time.zone.now.at_beginning_of_week.strftime('%Y-%m-%d')) }
  scope :current_month, -> { where('date >= :date', date: Time.zone.now.at_beginning_of_month.strftime('%Y-%m-%d')) }
  scope :sum_price_and_distance, -> { select('sum(price) as price, sum(distance) as distance') }
  # MySQL: group_concat(corporations.name)
  # PostgreSQL: string_agg(corporations.name, ',')
  # Oracle: listagg(corporations.name, ',')
  scope :sum_distance_avg_distance_avg_price,
        lambda {
          select('sum(distance) as sum_distance,
                  avg(price) as avg_price, avg(distance) as avg_distance,
                  date,
                  GROUP_CONCAT(DISTINCT corporations.name) as corporations').joins(:corporation)
        }

  belongs_to :corporation

  validates :start_address, :destination_address, :user, :date, :price, :distance, :corporation, presence: true
  validates :start_address, :destination_address, :user, length: { maximum: 256 }
  validates :price, numericality: { greater_than_or_equal_to: 0.0 }
  validates :distance, numericality: { greater_than: 0.0, message: 'error. Check your address' }

  before_validation :count_distance

  delegate :name, to: :corporation, prefix: true

  # custom setter (changing comma to dot)
  def price=(val)
    val.sub!(',', '.') if val.is_a?(String)
    self['price'] = val
  end

  private

  # Counting distance from start to destination location
  def count_distance
    # check if similar ride exist in db, if yes take distance from it else count it
    ride = Ride.find_by_start_address_and_destination_address(start_address, destination_address)
    ride ? self.distance = ride.distance : self.distance = geo_count_distance(start_address, destination_address)
  end
end

app/controllers/application_controller.rb
# Application Controller
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :current_user

  def current_user
    @current_user ||= generate_token
  end

  private

  def generate_token
    cookies[:user] ? cookies.signed[:user] : cookies.permanent.signed[:user] = SecureRandom.uuid
  end
end

app/controllers/rides_controller.rb
# Rides Controller
class RidesController < ApplicationController
  before_action :set_ride, only: [:show, :edit, :update, :destroy]

  # GET /rides
  # GET /rides.json
  def index
    @rides = Ride.by_user_with_corporations current_user
  end

  # GET /rides/1
  # GET /rides/1.json
  def show
  end

  # GET /rides/new
  def new
    @ride = Ride.new
  end

  # GET /rides/1/edit
  def edit
  end

  # POST /rides
  # POST /rides.json
  def create
    @ride = Ride.new(ride_params.merge(user: current_user))
    respond_to do |format|
      if @ride.save
        format.html { redirect_to @ride, notice: 'Ride was successfully created.' }
        # format.json { render :show, status: :created, location: @ride }
      else
        format.html { render :new }
        # format.json { render json: @ride.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rides/1
  # PATCH/PUT /rides/1.json
  def update
    respond_to do |format|
      if @ride.update(ride_params)
        format.html { redirect_to @ride, notice: 'Ride was successfully updated.' }
        # format.json { render :show, status: :ok, location: @ride }
      else
        format.html { render :edit }
        # format.json { render json: @ride.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rides/1
  # DELETE /rides/1.json
  def destroy
    @ride.destroy
    respond_to do |format|
      format.html { redirect_to rides_url, notice: 'Ride was successfully destroyed.' }
      # format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_ride
    @ride = Ride.find_by_id_and_user(params[:id], current_user)
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def ride_params
    params.require(:ride).permit(:corporation_id, :start_address, :destination_address, :date, :price)
  end
end

app/controllers/statistics_controller.rb
# Stats Controller
class StatisticsController < ApplicationController
  def index
    # How many kilometers rode during current week and how much money spent on the rides
    @week_stats = Ride.sum_price_and_distance.current_week.by_user(current_user)
    # Summary of ride distances from current month, grouped by day.
    @month_stats = Ride.sum_distance_avg_distance_avg_price.current_month.by_user(current_user).group(:date)
  end
end

app/helpers/application_helper.rb
# Application Helper
module ApplicationHelper
  # short version of number to currency, only for euro
  def number_to_eur(number)
    number_to_currency(number, unit: 'EUR', precision: 2, format: '%n %u')
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Riderank</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <!--Let browser know website is optimized for mobile-->
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <%= render 'shared/header' %>
    <%= render 'shared/alerts' %>
  </header>
  <main>
    <div class="container">
      <%= yield %>
    </div>
  </main>
</body>
</html>

app/views/rides/_alerts.html.erb
<script>
  Materialize.toast('<i class="material-icons">error_outline</i> &nbsp;&nbsp;&nbsp; <%= message %>', 4000, 'red darken-1');
</script>

app/views/rides/_form.html.erb
<div id="actors" class="row">
  <div class="col s12 m9">
    <%= form_for(ride, html: {class: 'form-class'}) do |f| %>
      <% if ride.errors.any? %>
        <%= render partial: 'alerts', collection: ride.errors.full_messages, as: :message %>
      <% end %>

      <div class="row">
        <div class="input-field col s12">
          <%= f.label :start_address %>
          <%= f.text_field :start_address, length: '255', class: 'validate', placeholder: 'Street 4, City, Country' %>
        </div>
      </div>
      <div class="row">
          <div class="input-field col s12">
            <%= f.label :destination_address %>
            <%= f.text_field :destination_address, length: '255', class: 'validate', placeholder: 'Street 6, City, Country' %>
          </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <%= f.label :date %>
          <%= f.text_field :date, class: 'datepicker', :value => Time.zone.now.strftime('%d %B, %Y') %>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <%= f.label :price %>
          <%= f.text_field :price, class: 'validate' %>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <%= f.collection_select(:corporation_id, Corporation.active, :id, :name,  include_blank: 'Select corporation', class: 'validate') %>
          <%= f.label :corporation %>
        </div>
      </div>

      <button class="btn waves-effect waves-light btn" type="submit" name="action">
        Submit
      </button>
    <% end %>
    </div>
</div>

app/views/rides/_ride.html.erb
<tr>
  <td><%= ride.date.strftime('%d %B, %Y') %></td>
  <td><%= ride.start_address %></td>
  <td><%= ride.destination_address %></td>
  <td><%= number_with_precision(ride.distance, precision: 2) %>km</td>
  <td><%= number_to_eur(ride.price) %></td>
  <td><%= ride.corporation_name %></td>
  <td><%= link_to 'Show', ride %></td>
  <td><%= link_to 'Edit', edit_ride_path(ride) %></td>
  <td><%= link_to 'Destroy', ride, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/rides/edit.html.erb
<div class="row">
  <h5>Editing Ride</h5>

  <%= render 'form', ride: @ride %>

  <%= link_to 'Show', @ride %> |
  <%= link_to 'Back', rides_path %>
</div>

app/views/rides/index.html.erb
<h3>Listing Rides</h3>
<%= link_to raw('<i class="material-icons">add</i>'),
            new_ride_path,
            class: 'btn-floating btn-large waves-effect waves-light' %>

<table class="centered responsive-table highlight">
  <thead>
    <tr>
      <th>Date</th>
      <th>Start address</th>
      <th>Destination address</th>
      <th>Distance</th>
      <th>Price</th>
      <th>Corporation</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render(@rides) || raw('<tr><td colspan="9">No rides registered</td></tr>') %>
  </tbody>
</table>

app/views/rides/new.html.erb
<div class="row">
  <h5>New Ride</h5>

  <%= render 'form', ride: @ride %>

  <%= link_to 'Back', rides_path %>
</div>

app/views/rides/show.html.erb
<p class="flow-text">
  <strong>Date:</strong>
  <%= @ride.date.strftime('%d %B, %Y')  %>
</p>

<p class="flow-text">
  <strong>Corporation:</strong>
  <%= @ride.corporation_name %>
</p>

<p class="flow-text">
  <strong>Start address:</strong>
  <%= @ride.start_address %>
</p>

<p class="flow-text">
  <strong>Destination address:</strong>
  <%= @ride.destination_address %>
</p>

<p class="flow-text">
  <strong>Distance:</strong>
  <%= number_with_precision(@ride.distance, precision: 2) %>km
</p>

<p class="flow-text">
  <strong>Price:</strong>
  <%= number_to_currency(@ride.price, unit:'EUR', precision: 2,format: '%n %u')%>
</p>

<%= link_to raw('<i class="material-icons">add</i>'),
            new_ride_path,
            class: 'btn-floating btn-large waves-effect waves-light' %>
<br>
<%= link_to 'Edit', edit_ride_path(@ride) %> |
<%= link_to 'Back', rides_path %>

app/views/shared/_alerts.html.erb
<% if notice %>
  <script>
    Materialize.toast('<i class="material-icons">done</i> &nbsp;&nbsp;&nbsp; <%= notice %>', 4000, 'green darken-1');
  </script>
<% end %>

<% if alert %>
  <script>
    Materialize.toast('<i class="material-icons">error_outline</i> &nbsp;&nbsp;&nbsp; <%= alert %>', 4000, 'red darken-1');
  </script>
<% end %>

app/views/shared/_header.html.erb
<nav>
  <div class="nav-wrapper">
    <%= link_to('Riderank', root_path, class: 'brand-logo') %>
    <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
    <ul class="right hide-on-med-and-down">
      <%= render 'shared/menu_links' %>
    </ul>
    <ul class="side-nav" id="mobile-demo">
      <%= render 'shared/menu_links' %>
    </ul>
  </div>
</nav>

app/views/shared/_menu_links.html.erb
<%= active_link_to 'Rides', rides_path, :wrap_tag => :li %>
<%= active_link_to 'Statistics', statistics_index_path, :wrap_tag => :li %>

app/views/statistics/_month_stats.erb
<tr>
  <td><%= data.date.strftime('%d %B, %Y') %></td>
  <td><%= number_with_precision(data.sum_distance, precision: 2)  %>km </td>
  <td><%= number_with_precision(data.avg_distance, precision: 2)  %>km </td>
  <td><%= number_to_eur(data.avg_price) %></td>
  <td><%= data.corporations.to_s.gsub(',', ', ') %></td>
</tr>

app/views/statistics/index.html.erb
<h3>Statistics</h3>

<div class="section">
  <h5>Week statistic</h5>
  <p>In this week (from: <%= Time.zone.now.at_beginning_of_week.strftime('%d %B, %Y') %>): </p>
  <% if !@week_stats.nil? %>
    <p>Distance: <%= number_with_precision(@week_stats.first.distance, precision: 2) || 0 %>km</p>
    <p>Price: <%= number_to_eur(@week_stats.first.price) || 'None' %></p>
  <% else %>
    <p>No rides registered</p>
  <% end %>
</div>
<div class="divider"></div>
<div class="section">
  <h5>Month statistic</h5>
  <p>In this month (from: <%= Time.zone.now.at_beginning_of_month.strftime('%d %B, %Y') %>): </p>
  <table class="centered responsive-table highlight">
    <thead>
    <tr>
      <th>Date</th>
      <th>Rides sum</th>
      <th>Avg. ride</th>
      <th>Avg. price</th>
      <th>Taxis</th>
    </tr>
    </thead>

    <tbody>
      <%= render(partial: 'month_stats', collection: @month_stats, as: :data) ||
                  raw('<tr><td colspan="5">No rides registered</td></tr>')    %>
    </tbody>
  </table>
</div>